export const tripMeta = {
  dates: '2026.09.19 — 09.29',
  people: '5 位旅人',
  nights: '11 天 10 夜',
}

const item = (time, title, place, detail = '', branch = 'all') => ({ time, title, place, detail, branch })

export const itinerary = [
  {
    day: 1, date: '2026-09-19', weekday: '六', city: '台北 → 奧克蘭', icon: '✦',
    theme: '暫別台北，飛往長白雲之鄉', stay: '機上 On Board', budget: '$0（機票已預付）',
    transport: '飛機｜TPE → AKL，約 10 小時 50 分',
    note: '紐西蘭入境檢疫嚴格；勿攜帶生鮮肉類與蔬果，戶外裝備與鞋底請預先刷洗。',
    items: [
      item('15:30', '抵達桃園國際機場', '桃園國際機場', '紐西蘭航空報到與行李託運'),
      item('18:30', '搭乘 NZ78 飛往奧克蘭', '桃園國際機場第二航廈', '機上晚餐與休息'),
    ],
  },
  {
    day: 2, date: '2026-09-20', weekday: '日', city: '皇后鎮 Queenstown', icon: '❄',
    theme: '抵達皇后鎮，滑雪整備與湖畔自炊', stay: 'Quest Queenstown', budget: '約 $250 NZD＋雪具租借',
    transport: '國內線 AKL → ZQN｜市區自駕，各點約 15 分鐘',
    note: '超市購酒需出示護照；初春晚間低溫，備妥防風保暖衣物。',
    items: [
      item('09:00', '機上早餐', 'Air New Zealand', '機上起床、享用早餐'),
      item('10:20', '抵達奧克蘭機場', 'Auckland Airport', '轉乘國內線 NZ637'),
      item('14:00', '抵達皇后鎮', 'Queenstown Airport'),
      item('15:30', '租車取車', 'Go Rentals Queenstown Airport'),
      item('16:00', '超市採購', "PAK'nSAVE Queenstown", '早餐食材、肋眼牛排與紅白酒'),
      item('17:00', '飯店 Check-in', 'Quest Queenstown Apartments'),
      item('17:30', '雪具租借／湖畔散步', 'Snow Centre Queenstown', '2 人租雪具；3 人湖畔散步'),
      item('19:30', '自炊晚餐', 'Quest Queenstown Apartments', '香煎紐西蘭肋眼牛排佐在地紅酒'),
    ],
  },
  {
    day: 3, date: '2026-09-21', weekday: '一', city: '皇后鎮 Queenstown', icon: '◒',
    theme: '卓越山脈春季滑雪 vs 皇后鎮經典觀光', stay: 'Quest Queenstown（續住）', budget: '滑雪組 $450–500／人；觀光組約 $150／人',
    transport: '滑雪組自駕往返雪場；觀光組市區步行',
    note: '熱門居酒屋建議提前訂位；雪地紫外線強，請配戴雪鏡並補擦防曬。',
    items: [
      item('08:30', '自製早餐', 'Quest Queenstown Apartments'),
      item('09:00', '私人滑雪教練課', 'The Remarkables Ski Area', '09:00–12:00 強化技巧', 'ski'),
      item('10:30', '天際纜車與 Luge', 'Skyline Queenstown', '登鮑伯峰俯瞰湖景', 'sightseeing'),
      item('12:00', '雪場午餐', 'The Remarkables Ski Area', '簡餐約 $25 NZD', 'ski'),
      item('13:00', '自由滑雪練習', 'The Remarkables Ski Area', '13:00–16:00', 'ski'),
      item('13:00', '景觀午餐', 'Stratosfare Restaurant & Bar', '自助餐或市區簡餐', 'sightseeing'),
      item('15:00', '皇后鎮花園漫步', 'Queenstown Gardens', '半島花園與湖光山色', 'sightseeing'),
      item('16:30', '市區逛街', 'Queenstown Mall', '紀念品與咖啡', 'sightseeing'),
      item('17:30', '歸還雪具', 'Snow Centre Queenstown', '', 'ski'),
      item('19:00', '日式鐵板燒晚餐', 'Tanoshi Queenstown', '推薦清酒，約 $100 NZD／人'),
    ],
  },
  {
    day: 4, date: '2026-09-22', weekday: '二', city: 'Glenorchy', icon: '♨',
    theme: '魔戒河谷騎馬涉水與溫泉放鬆', stay: 'Quest Queenstown（續住）', budget: '約 $800 NZD',
    transport: '自駕｜Queenstown → Glenorchy 約 45 分鐘',
    note: '騎馬穿長褲與包鞋；Onsen 極熱門，建議提早預訂 18:30 場次。',
    items: [
      item('09:00', '自製早餐', 'Quest Queenstown Apartments'),
      item('10:30', '格溫諾奇小鎮漫遊', 'Glenorchy Red Shed', '紅屋碼頭與湖畔步道'),
      item('12:30', '小鎮午餐', 'Glenorchy Cafe', '在地簡餐與咖啡'),
      item('14:15', '騎馬活動報到', 'High Country Horses'),
      item('14:30', 'Rees River Trail 騎馬', 'High Country Horses', '14:30–17:00，雪山河谷與涉水體驗'),
      item('18:30', '私人景觀溫泉', 'Onsen Hot Pools', '約 1 小時'),
      item('20:00', '名廚晚餐', 'Rātā Restaurant', '推薦威靈頓牛排'),
    ],
  },
  {
    day: 5, date: '2026-09-23', weekday: '三', city: '皇后鎮 Queenstown', icon: '≈',
    theme: '莫克湖探險與峽谷噴射快艇', stay: 'Quest Queenstown（續住）', budget: '蒸汽船約 $80／人；晚餐約 $120／人',
    transport: '自駕｜市區 → Moke Lake 20 分；Moke Lake → 快艇 25 分',
    note: 'Canyon Brewing 就在快艇報到處旁，快艇組用餐後可直接步行報到。',
    items: [
      item('09:00', '自製早餐', 'Quest Queenstown Apartments'),
      item('10:30', '出發前往秘境', 'Moke Lake'),
      item('11:00', '莫克湖與鮑勃灣', "Moke Lake", "高山湖泊倒影與 Bob's Cove 綠松石湖水"),
      item('12:30', '峽谷精釀午餐', 'Canyon Brewing'),
      item('14:00', '快艇報到', 'Shotover Jet', '', 'jetboat'),
      item('14:30', 'Shotover Jet', 'Shotover Jet', '14:30–15:30，360° 峽谷甩尾', 'jetboat'),
      item('14:30', '百年蒸汽船巡湖', 'TSS Earnslaw', '約 1.5 小時', 'leisure'),
      item('17:00', '市區會合', 'Queenstown Bay'),
      item('18:30', '湖景牛排晚餐', 'Botswana Butchery Queenstown'),
    ],
  },
  {
    day: 6, date: '2026-09-24', weekday: '四', city: 'Wanaka → Twizel', icon: '✧',
    theme: '瓦納卡快閃與特威澤爾極光之夜', stay: 'Mountain Chalets Motel', budget: '約 $100 NZD',
    transport: '自駕｜Queenstown → Wanaka 1 小時 → Twizel 2 小時',
    note: '特威澤爾位於國際暗空保護區，建議用 Aurora App 追蹤 KP 值。',
    items: [
      item('09:00', '早餐、退房', 'Quest Queenstown Apartments'),
      item('10:30', '翻越皇冠山脈公路', 'Crown Range Road'),
      item('11:30', '瓦納卡孤獨樹', '#ThatWanakaTree'),
      item('12:30', '酒莊高點賞湖', 'Rippon Winery', '拍照，免門票'),
      item('13:00', '沿途簡餐', 'Wānaka'),
      item('14:00', '前往特威澤爾', 'Twizel'),
      item('16:00', '鮭魚產地採購', 'High Country Salmon'),
      item('17:30', '飯店 Check-in', 'Mountain Chalets Motel'),
      item('19:00', '鮭魚生魚片自炊', 'Mountain Chalets Motel'),
      item('21:00', '自主觀星與極光監測', 'Twizel', '無光害陽台觀賞銀河'),
    ],
  },
  {
    day: 7, date: '2026-09-25', weekday: '五', city: 'Aoraki / Mount Cook', icon: '△',
    theme: '庫克山冰河探險與星空守候', stay: 'Mountain Chalets Motel（續住）', budget: '約 $160 NZD',
    transport: '自駕｜Twizel ↔ Mount Cook，單程約 45 分鐘',
    note: '山區天氣多變，健行備妥防風保暖衣物、水與輕便零食。',
    items: [
      item('09:00', '自製早餐', 'Mountain Chalets Motel'),
      item('10:30', '前往庫克山', 'Aoraki / Mount Cook National Park'),
      item('11:30', '胡克谷步道健行', 'Hooker Valley Track', '三座吊橋、庫克山與冰河湖，來回 3–4 小時'),
      item('14:30', '雪山景觀午餐', "The Old Mountaineers' Cafe"),
      item('16:00', '隱士飯店咖啡', 'The Hermitage Hotel'),
      item('19:00', '特威澤爾晚餐', 'Poppies Cafe Twizel'),
      item('21:00', '自主觀星', 'Twizel', '暗空保護區最後一夜'),
    ],
  },
  {
    day: 8, date: '2026-09-26', weekday: '六', city: 'Tekapo → Christchurch', icon: '◌',
    theme: '夢幻乳藍湖水與前進基督城', stay: 'Sudima Christchurch City', budget: '約 $150 NZD',
    transport: '自駕｜Twizel → Tekapo 40 分鐘 → Christchurch 約 3 小時',
    note: '約翰山天文台收費車道通常 17:00 關閉，留意下山時間。',
    items: [
      item('09:00', '早餐、退房', 'Mountain Chalets Motel'),
      item('11:15', '蒂卡波湖與好牧羊人教堂', 'Church of the Good Shepherd'),
      item('12:30', '日式鮭魚丼午餐', 'Kohan Restaurant'),
      item('14:00', '約翰山天文台', 'Mt John Observatory', '喝咖啡俯瞰乳藍湖景'),
      item('16:15', '手工肉派點心', 'Fairlie Bakehouse'),
      item('18:30', '基督城飯店 Check-in', 'Sudima Christchurch City'),
      item('19:00', '市區簡餐或自炊', 'Christchurch Central City'),
    ],
  },
  {
    day: 9, date: '2026-09-27', weekday: '日', city: 'Christchurch', icon: '⌁',
    theme: '基督城慢活與地標餐廳晚宴', stay: 'Sudima Christchurch City（續住）', budget: '電車與晚餐約 $400 NZD／2 人',
    transport: '市區步行或搭乘復古電車',
    note: 'Twenty Seven Steps 極熱門，建議立刻預訂 19:30 時段。',
    items: [
      item('09:30', '睡到自然醒、早餐', 'Sudima Christchurch City'),
      item('11:00', '基督城十道美食導覽', 'Christchurch Central City', '11:00–14:00', 'food'),
      item('11:30', '河畔市集早午餐', 'Riverside Market', '', 'british'),
      item('13:00', '基督城植物園', 'Christchurch Botanic Gardens', '', 'british'),
      item('14:30', '兩組會合', 'Christchurch Central City'),
      item('15:00', '復古電車城市巡遊', 'Christchurch Tram', '隨上隨下'),
      item('19:30', '新攝政街晚宴', 'Twenty Seven Steps'),
    ],
  },
  {
    day: 10, date: '2026-09-28', weekday: '一', city: 'Christchurch → Auckland', icon: '↗',
    theme: '城市最後巡禮與飛往奧克蘭', stay: '奧克蘭機場周邊（待訂）', budget: '約 $160 NZD',
    transport: '自駕還車｜CHC → AKL 國內線約 1.5 小時',
    note: '還車前於機場附近加滿油並保留收據；Novotel 距國際航廈步行 1 分鐘。',
    items: [
      item('09:00', '早餐', 'Christchurch Central City'),
      item('11:00', '市區最後採買', 'Christchurch Central City', '麥蘆卡蜂蜜與羊毛製品'),
      item('13:00', '市區簡餐', 'Christchurch Central City'),
      item('15:30', '租車還車', 'Go Rentals Christchurch Airport', '先加滿油'),
      item('17:00', '飛往奧克蘭', 'Christchurch Airport'),
      item('19:00', '奧克蘭飯店 Check-in', 'Auckland Airport'),
      item('19:30', '機場飯店晚餐', 'Auckland Airport'),
    ],
  },
  {
    day: 11, date: '2026-09-29', weekday: '二', city: '奧克蘭 → 台北', icon: '⌂',
    theme: '帶著滿滿回憶回台灣', stay: '溫暖的家', budget: '$0（機票已預付）',
    transport: '步行至航廈｜AKL → TPE，約 11 小時',
    note: '出境與安檢需時較長，請準時抵達機場。',
    items: [
      item('07:30', '起床、早餐', 'Auckland Airport Hotel'),
      item('08:00', '步行至國際航廈', 'Auckland International Terminal', '辦理登機與行李託運'),
      item('10:00', '搭乘 NZ77 回台北', 'Auckland International Terminal'),
      item('18:00', '抵達桃園國際機場', '桃園國際機場', '傍晚抵達，時間為預估'),
    ],
  },
]

const restaurant = (name, type, note) => ({ name, type, note })
const sight = (name, type, note) => ({ name, type, note })

export const regions = [
  {
    id: 'queenstown', name: '皇后鎮', en: 'Queenstown', tagline: '山湖之間，留一點餘裕給驚喜',
    restaurants: [
      restaurant('Vudu Cafe & Larder', '早午餐', '湖畔人氣早午餐，烘焙與咖啡都穩定'),
      restaurant('The Exchange', '咖啡輕食', '明亮舒適，適合快速早餐'),
      restaurant('Odd Saint', '創意早午餐', '蔬食友善、擺盤漂亮'),
      restaurant('Jervois Steak House', '精緻牛排', '熟成牛排與酒單完整'),
      restaurant('Blue Kanu', '太平洋融合料理', '亞洲與太平洋島嶼風味混搭'),
      restaurant('Margo’s', '墨西哥料理', '氣氛活潑，適合多人分食'),
      restaurant('Ivy & Lola’s', '紐西蘭料理', '碼頭景觀與在地海鮮'),
      restaurant('Fergbaker', '在地烘焙', '鹹派、可頌與外帶早餐'),
      restaurant('Saigon Kingdom', '越南料理', '暖胃河粉，旅行中換口味'),
      restaurant('Smiths Craft Beer House', '精釀酒吧', '紐西蘭精釀選擇豐富'),
    ],
    sights: [
      sight('Kiwi Park Queenstown', '室內／雨天', '保育導覽與奇異鳥夜行館'),
      sight('Thrillzone Queenstown', '室內／雨天', 'VR 與團體互動遊戲'),
      sight('Queenstown Arts Centre', '室內／雨天', '小型展覽與在地藝術'),
      sight('Lake Hayes Walkway', '室外', '平緩環湖步道與鏡面湖景'),
      sight('Arrow River Trail', '室外', '河谷散步與淘金小鎮氛圍'),
      sight('Bennett’s Bluff Lookout', '室外', '沿湖公路的壯闊觀景點'),
    ],
  },
  {
    id: 'twizel', name: '特威澤爾', en: 'Twizel', tagline: '暗空之下，慢慢吃、靜靜看',
    restaurants: [
      restaurant('The Musterer’s Hut Cafe', '早午餐', '木屋氛圍與豐盛早餐'),
      restaurant('Hydro Cafe', '咖啡輕食', '在地人日常咖啡館'),
      restaurant('Fishtail Restaurant', '印度料理', '咖哩選擇多且暖胃'),
      restaurant('Ministry of Works Bar & Eatery', '酒吧餐館', '精釀啤酒與漢堡'),
      restaurant('Jasmine Thai', '泰式料理', '多人分享方便'),
      restaurant('Top Hut Bar & Bistro', '紐西蘭餐酒館', '份量實在的經典餐點'),
      restaurant('Power Station Bristro', '現代紐西蘭料理', '安靜舒適的晚餐選擇'),
      restaurant('Sweet Moos Ice Cream', '甜點', '旅行途中的冰淇淋補給'),
      restaurant('Twizel Bakery Cafe', '在地烘焙', '肉派與快速早餐'),
      restaurant('Razza Bar', '酒吧小吃', '輕鬆的夜間聚會選擇'),
    ],
    sights: [
      sight('Te Ana Māori Rock Art Centre', '室內／雨天', '認識南島毛利岩畫文化'),
      sight('Sir Edmund Hillary Alpine Centre', '室內／雨天', '登山史、天文館與數位劇場'),
      sight('Lakeland Explorer Gallery', '室內／雨天', '麥肯錫地區攝影與風景作品'),
      sight('Lake Ruataniwha', '室外', '平靜湖畔與短程散步'),
      sight('Pyramid Saddle Viewpoint', '室外', '遼闊高地與山景'),
      sight('Ben Ohau Wetland Track', '室外', '短程濕地步道與觀鳥'),
    ],
  },
  {
    id: 'christchurch', name: '基督城', en: 'Christchurch', tagline: '花園城市裡，新與舊剛剛好',
    restaurants: [
      restaurant('Miro', '早午餐', '老建築中的精緻早餐'),
      restaurant('Unknown Chapter Coffee Roasters', '咖啡早午餐', '自家烘豆與豐盛早午餐'),
      restaurant('Child Sister', '亞洲融合早午餐', '韓式元素與現代咖啡館'),
      restaurant('5th Street', '分享料理', '適合五人分享的季節菜單'),
      restaurant('Bessie', '精緻牛排', '炭火熟成肉品專門'),
      restaurant('King of Snake', '亞洲料理', '華麗空間與東南亞風味'),
      restaurant('Earl', '現代歐陸料理', '簡潔成熟的餐酒搭配'),
      restaurant('SUPER', '日韓融合料理', '輕鬆有趣的小盤料理'),
      restaurant('Smokey T’s', '美式燒烤', '慢燻肉與豪邁份量'),
      restaurant('Punky Brewster', '精釀酒吧', '大量紐西蘭精釀與休閒氣氛'),
    ],
    sights: [
      sight('Tūranga Central Library', '室內／雨天', '建築設計、城市視野與免費展區'),
      sight('Quake City', '室內／雨天', '理解城市地震歷史與重建'),
      sight('The Arts Centre Te Matatiki Toi Ora', '室內／雨天', '哥德復興建築與藝文空間'),
      sight('New Brighton Pier', '室外', '海岸長堤與日出景色'),
      sight('Port Hills Summit Road', '室外', '俯瞰城市與坎特伯雷平原'),
      sight('Mona Vale Garden Park', '室外', '英式宅邸花園與雅芳河支流'),
    ],
  },
]

export const highlights = [
  ['01', '低頻換宿', '皇后鎮連住四晚、特威澤爾連住兩晚，把時間還給睡眠與風景。'],
  ['02', '頂級與自炊', '名店晚宴、肋眼牛排與產地鮭魚，讓儀式感和生活感並存。'],
  ['03', '彈性分組', '滑雪與經典觀光、快艇與蒸汽船，每個人都能選自己的步調。'],
  ['04', '春雪與暗空', '九月春雪、麥肯錫暗空保護區，守候銀河與南極光。'],
  ['05', '海陸空視角', '滑雪、騎馬、快艇與高山公路，多角度感受南島地貌。'],
]
